language: node_js
node_js:
  - "node"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g tslint


script:
  - ng test --single-run
  - ng build --aot -prod
