language: node_js
node_js:
  - "node"

sudo: required
addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g tslint
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start

script:
  - ng test --single-run
  - ng build --aot -prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  